# Generated by Django 5.2 on 2025-05-16 17:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(default='No especificado', help_text='Lugar de encuentro para la asesoría', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Administrador', 'Administrador'), ('Director', 'Director')], default='Estudiante', max_length=13)),
                ('subtipo_director', models.CharField(blank=True, max_length=50, null=True)),
                ('subtipo_docente', models.CharField(blank=True, max_length=50, null=True)),
                ('semestre', models.CharField(blank=True, choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre'), ('3', 'Tercer Semestre'), ('4', 'Cuarto Semestre'), ('5', 'Quinto Semestre'), ('6', 'Sexto Semestre'), ('7', 'Séptimo Semestre'), ('8', 'Octavo Semestre'), ('9', 'Noveno Semestre'), ('10', 'Décimo Semestre')], max_length=2, null=True)),
                ('grupo', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subtipo_director', models.CharField(max_length=50)),
                ('director_creador', models.ForeignKey(limit_choices_to={'rol': 'Director'}, on_delete=django.db.models.deletion.CASCADE, related_name='areas_creadas', to=settings.AUTH_USER_MODEL)),
                ('docentes', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'Docente'}, related_name='areas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('semestre', models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre'), ('3', 'Tercer Semestre'), ('4', 'Cuarto Semestre'), ('5', 'Quinto Semestre'), ('6', 'Sexto Semestre'), ('7', 'Séptimo Semestre'), ('8', 'Octavo Semestre'), ('9', 'Noveno Semestre'), ('10', 'Décimo Semestre')], max_length=2)),
                ('usar_docentes_area', models.BooleanField(default=True)),
                ('subtipo_director', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='usuarios.area')),
                ('director_creador', models.ForeignKey(limit_choices_to={'rol': 'Director'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('docentes', models.ManyToManyField(blank=True, related_name='asignaturas_dictadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('En curso', 'En curso'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Aprobada', max_length=15)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('asistio', models.BooleanField(default=False, help_text='Indica si el estudiante asistió a la asesoría')),
                ('temas_tratados', models.TextField(blank=True, help_text='Temas abordados durante la asesoría', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del docente', null=True)),
                ('compromisos', models.TextField(blank=True, help_text='Compromisos adquiridos para futuras asesorías', null=True)),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Calificación del 1 al 5', null=True)),
                ('comentario_calificacion', models.TextField(blank=True, help_text='Comentarios sobre la asesoría', null=True)),
                ('fecha_calificacion', models.DateTimeField(blank=True, help_text='Fecha en que se calificó la asesoría', null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorias_impartidas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorias_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorias', to='usuarios.asignatura')),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorias', to='usuarios.bloquehorario')),
            ],
            options={
                'verbose_name': 'Asesoría',
                'verbose_name_plural': 'Asesorías',
            },
        ),
        migrations.CreateModel(
            name='AsesoriaBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False, help_text='Indica si el estudiante asistió a este bloque de asesoría')),
                ('docente_asistio', models.BooleanField(default=False, help_text='Indica si el docente asistió a este bloque de asesoría (registrado por el estudiante)')),
                ('temas_tratados', models.TextField(blank=True, help_text='Temas abordados durante este bloque', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales para este bloque', null=True)),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_asesoria', to='usuarios.asesoria')),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorias_bloques', to='usuarios.bloquehorario')),
            ],
            options={
                'verbose_name': 'Bloque de Asesoría',
                'verbose_name_plural': 'Bloques de Asesorías',
                'unique_together': {('asesoria', 'bloque_horario')},
            },
        ),
        migrations.AddField(
            model_name='asesoria',
            name='bloques_horario',
            field=models.ManyToManyField(related_name='asesorias_relacionadas', through='usuarios.AsesoriaBloque', to='usuarios.bloquehorario'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(default='2025-1', max_length=10)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('docente', 'periodo', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='usuarios.horario'),
        ),
        migrations.CreateModel(
            name='PermisoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_crear_horarios', models.BooleanField(default=False)),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de docente',
                'verbose_name_plural': 'Permisos de docentes',
            },
        ),
        migrations.CreateModel(
            name='PermisoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.horario')),
            ],
            options={
                'verbose_name': 'Permiso de horario',
                'verbose_name_plural': 'Permisos de horarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bloquehorario',
            unique_together={('horario', 'fecha', 'hora_inicio', 'hora_fin')},
        ),
    ]
