# Generated by Django 5.1.6 on 2025-04-08 19:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Administrador', 'Administrador'), ('Director', 'Director')], default='Estudiante', max_length=13)),
                ('subtipo_director', models.CharField(blank=True, max_length=50, null=True)),
                ('subtipo_docente', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subtipo_director', models.CharField(max_length=50)),
                ('director_creador', models.ForeignKey(limit_choices_to={'rol': 'Director'}, on_delete=django.db.models.deletion.CASCADE, related_name='areas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('semestre', models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre'), ('3', 'Tercer Semestre'), ('4', 'Cuarto Semestre'), ('5', 'Quinto Semestre'), ('6', 'Sexto Semestre'), ('7', 'Séptimo Semestre'), ('8', 'Octavo Semestre'), ('9', 'Noveno Semestre'), ('10', 'Décimo Semestre')], max_length=2)),
                ('subtipo_director', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='usuarios.area')),
                ('director_creador', models.ForeignKey(limit_choices_to={'rol': 'Director'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('docentes', models.ManyToManyField(related_name='asignaturas_dictadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(default='2025-1', max_length=10)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('docente', 'periodo', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='usuarios.horario')),
            ],
            options={
                'unique_together': {('horario', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
