# Generated by Django 5.2 on 2025-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoriabloque',
            name='docente_confirma_asistencia',
            field=models.BooleanField(default=False, help_text='Confirmación por el docente de que asistió a este bloque de asesoría'),
        ),
    ]
