# Generated by Django 5.1.6 on 2025-04-09 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'Docente'}, related_name='areas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='usar_docentes_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='asignaturas_dictadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
