# Generated by Django 5.1.6 on 2025-04-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_area_docentes_asignatura_usar_docentes_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.horario')),
            ],
            options={
                'verbose_name': 'Permiso de horario',
                'verbose_name_plural': 'Permisos de horarios',
            },
        ),
    ]
